name: Test
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15.8
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.8

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: |
          make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: xbar_github_status.5m.cgo
          path: ./bin/xbar_github_status.5m.cgo
