name: Test
on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15.8
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.8

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: |
          make test
